{
 "title": "Redpanda Ops Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   { "name": "node", "label": "Node", "query": { "query": "label_values(instance)" } },
   {
    "name": "exported_node",
    "label": "Exported Node",
    "query": {
     "query": "label_values(exported_instance)"
    }
   },
   { "name": "node_shard", "label": "Shard", "query": { "query": "label_values(shard)" } },
   {
    "name": "aggr_criteria",
    "label": "Aggregate by",
    "query": "cluster, pod, instance, shard, instance\\,shard, pod\\,shard"
   },
   {
    "name": "data_cluster",
    "label": "Data cluster",
    "query": {
     "query": "label_values(redpanda_cloud_data_cluster_name)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<h1 style=\"color:#87CEEB; border-bottom: 3px solid #87CEEB;\">Redpanda Summary</h1>"
   }
  },
  {
   "title": "Nodes Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count  by (app) (redpanda_application_uptime_seconds_total{redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}) OR on() vector(0)",
     "legendFormat": "Nodes Up"
    },
    {
     "expr": "max_over_time(count by (app) (redpanda_application_uptime_seconds_total{redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}   )[1w:])",
     "legendFormat": "Nodes Up"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (exported_instance, instance) (redpanda_application_uptime_seconds_total{instance=~\"[[node]]\", exported_instance=~\"[[exported_node]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"})",
     "legendFormat": "{{instance}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redpanda_cluster_topics) by ([[aggr_criteria]])",
     "legendFormat": "Partition count"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by([[aggr_criteria]])(rate(redpanda_kafka_request_bytes_total[1m]))",
     "legendFormat": "Partition count"
    }
   ]
  },
  {
   "title": "Leadership Transfers / 5min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(redpanda_raft_leadership_changes{redpanda_cloud_data_cluster_name=\"[[data_cluster]]\"}[5m])) ",
     "legendFormat": "Pod: {{pod}}, Node: {{instance}}"
    }
   ]
  },
  {
   "title": "Under replicated partitions by topic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (redpanda_kafka_under_replicated_replicas{redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}) > 0 OR on() vector(0)  ",
     "legendFormat": "{{topic}}/{{namespace}}/{{redpanda_cloud_data_cluster_name}}"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(min by(redpanda_topic) (redpanda_kafka_partitions{redpanda_cloud_data_cluster_name=~\"\"}))",
     "legendFormat": "Partition count"
    }
   ]
  },
  {
   "title": "Partition Offset Balance Deviation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * abs(1-(sum(stddev by (redpanda_topic) (sum(redpanda_kafka_max_offset{redpanda_namespace=\"kafka\",redpanda_cloud_data_cluster_name=~\"\"}) by (redpanda_topic,redpanda_partition))) /  sum(avg by (redpanda_topic) ((sum(redpanda_kafka_max_offset{redpanda_namespace=\"kafka\",redpanda_cloud_data_cluster_name=~\"\"}) by (redpanda_topic,redpanda_partition))))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leaderless Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum  (redpanda_cluster_unavailable_partitions{redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"} == -1) OR on() vector(0) + sum(max by(redpanda_namespace, redpanda_topic) (redpanda_kafka_partitions ) - count by(redpanda_namespace, redpanda_topic) (count by (redpanda_namespace, redpanda_topic, redpanda_partition) (redpanda_kafka_under_replicated_replicas)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (\n  sum(redpanda_storage_disk_free_bytes{instance=~\".*\",shard=~\".*\",redpanda_cloud_data_cluster_name=~\"\"}) \n/\nsum(redpanda_storage_disk_total_bytes{instance=~\".*\",shard=~\".*\",redpanda_cloud_data_cluster_name=~\"\"}) \n))\n*\n100 ",
     "legendFormat": "Pod: {{pod}}, Node: {{instance}}, Shard: {{shard}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(deriv(redpanda_cpu_busy_seconds_total[$__rate_interval]))",
     "legendFormat": "Pod: {{pod}}, Node: {{instance}}, Shard: {{shard}}"
    }
   ]
  },
  {
   "title": "Kafka RPC: Currently active connections",
   "type": "timeseries",
   "description": "Shows the number of clients actively connected. A sudden, extreme change in this metric may indicate problems with connection.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redpanda_rpc_active_connections{instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}) by ([[aggr_criteria]])",
     "legendFormat": "Pod: {{pod}}, Node: {{instance}}, Shard: {{shard}}"
    }
   ]
  },
  {
   "title": "Cluster Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redpanda_application_build{redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"} * on (instance, exported_instance) group_left redpanda_application_uptime_seconds_total{instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redpanda_storage_disk_free_space_alert)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produce Latency",
   "type": "timeseries",
   "description": "Measured within Redpanda",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(redpanda_kafka_handler_latency_seconds_bucket{handler=\"produce\",exported_instance=~\"[[exported_node]]\",instance=~\"[[node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m])) by (le, [[aggr_criteria]]))",
     "legendFormat": "p99 Pod: {{pod}}, Node: {{instance}}, Shard: {{shard}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(redpanda_kafka_handler_latency_seconds_bucket{handler=\"produce\",exported_instance=~\"[[exported_node]]\",instance=~\"[[node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m] offset 1d)) by (le, cluster))",
     "legendFormat": "Yesterday cluster average (p99)"
    },
    {
     "expr": "histogram_quantile(0.95 , sum(rate(redpanda_kafka_handler_latency_seconds_bucket{handler=\"produce\",exported_instance=~\"[[exported_node]]\",instance=~\"[[node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m])) by (le, [[aggr_criteria]]))",
     "legendFormat": "p95 Pod: {{pod}}, Node: {{instance}}, Shard: {{shard}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(redpanda_kafka_handler_latency_seconds_bucket{handler=\"produce\",exported_instance=~\"[[exported_node]]\",instance=~\"[[node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m] offset 1d)) by (le, cluster))",
     "legendFormat": "Yesterday cluster average (p95)"
    }
   ]
  },
  {
   "title": "IO Queue Write Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(redpanda_io_queue_total_write_ops{instance=~\"[[node]]\", exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=\"[[data_cluster]]\"}[5m])) by ([[aggr_criteria]])",
     "legendFormat": "Pod: {{ pod }}"
    },
    {
     "expr": "sum(rate(redpanda_io_queue_total_write_ops{instance=~\"[[node]]\", exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=\"[[data_cluster]]\"}[5m] offset 1d)) by (cluster)",
     "legendFormat": "Yesterday cluster average"
    }
   ]
  },
  {
   "title": "Bytes Received via Kafka RPC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redpanda_kafka_request_bytes_total{instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_request=\"produce\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m])) by ([[aggr_criteria]])",
     "legendFormat": "Pod: {{pod}}, Node: {{instance}}, Shard: {{shard}}"
    }
   ]
  },
  {
   "title": "Fetch Latency ",
   "type": "timeseries",
   "description": "Measured within Redpanda",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(redpanda_kafka_handler_latency_seconds_bucket{handler=\"fetch\",instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m])) by (le, [[aggr_criteria]]))",
     "legendFormat": "p99 Pod: {{pod}}, Node: {{instance}}, Shard: {{shard}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(redpanda_kafka_handler_latency_seconds_bucket{handler=\"fetch\",instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m] offset 1d)) by (le, cluster))",
     "legendFormat": "Yesterday cluster average (p99)"
    },
    {
     "expr": "histogram_quantile(0.95 , sum(rate(redpanda_kafka_handler_latency_seconds_bucket{handler=\"fetch\",instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m])) by (le, [[aggr_criteria]]))",
     "legendFormat": "p95 Pod: {{pod}}, Node: {{instance}}, Shard: {{shard}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(redpanda_kafka_handler_latency_seconds_bucket{handler=\"fetch\",instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m] offset 1d)) by (le, cluster))",
     "legendFormat": "Yesterday cluster average (p95)"
    }
   ]
  },
  {
   "title": "IO Queue Read Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(redpanda_io_queue_total_read_ops{instance=~\"[[node]]\", exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=\"[[data_cluster]]\"}[5m])) by ([[aggr_criteria]])",
     "legendFormat": "Pod: {{pod}} Node: {{instance}} Partition: {{partition}} Shard: {{shard}}"
    },
    {
     "expr": "sum(rate(redpanda_io_queue_total_read_ops{instance=~\"[[node]]\", exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=\"[[data_cluster]]\"}[5m] offset 1d)) by (cluster)",
     "legendFormat": "Yesterday cluster average"
    }
   ]
  },
  {
   "title": "Bytes Sent via Kafka RPC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redpanda_kafka_request_bytes_total{instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_request=\"consume\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[30s])) by ([[aggr_criteria]])",
     "legendFormat": "Pod: {{pod}}, Node: {{instance}}, Shard: {{shard}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 },
   "options": {
    "content": "<h1 style=\"color:#87CEEB; border-bottom: 3px solid #87CEEB;\">Redpanda Memory</h1>"
   }
  },
  {
   "title": "Available memory",
   "type": "gauge",
   "description": "Free memory plus the memory occupied by the batch cache. This is how much memory Redpanda can allocate if needed after reclaim.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (exported_instance, instance) (redpanda_memory_available_memory{instance=~\"[[node]]\", exported_instance=~\"[[exported_node]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available memory low watermark",
   "type": "gauge",
   "description": "The lowest available memory over the lifetime of the node (the closest the node has been to out-of-memory).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (exported_instance, instance) (redpanda_memory_available_memory_low_water_mark{instance=~\"[[node]]\", exported_instance=~\"[[exported_node]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 47 },
   "options": {
    "content": "<h1 style=\"color:#87CEEB; border-bottom: 3px solid #87CEEB;\">Kafka Latency</h1>"
   }
  },
  {
   "title": "Produce Latency  (p95)",
   "type": "timeseries",
   "description": "Measured within Redpanda",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(redpanda_kafka_handler_latency_seconds_bucket{handler=\"produce\",instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m])) by (le, [[aggr_criteria]]))",
     "legendFormat": "Pod: {{pod}}, Node: {{instance}}, Shard: {{shard}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(redpanda_kafka_handler_latency_seconds_bucket{handler=\"produce\",instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m] offset 1d)) by (le, cluster))",
     "legendFormat": "Yesterday cluster avg"
    }
   ]
  },
  {
   "title": "Produce Latency  (p99)",
   "type": "timeseries",
   "description": "Measured within Redpanda",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(redpanda_kafka_handler_latency_seconds_bucket{handler=\"produce\",instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m])) by (le, [[aggr_criteria]]))",
     "legendFormat": "Pod: {{pod}}, Node: {{instance}}, Shard: {{shard}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(redpanda_kafka_handler_latency_seconds_bucket{handler=\"produce\",instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m] offset 1d)) by (le, cluster))",
     "legendFormat": "Yesterday cluster average"
    }
   ]
  },
  {
   "title": "Fetch Latency  (p95)",
   "type": "timeseries",
   "description": "Measured within Redpanda",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(redpanda_kafka_handler_latency_seconds_bucket{handler=\"fetch\",instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m])) by (le, [[aggr_criteria]]))",
     "legendFormat": "Pod: {{pod}}, Node: {{instance}}, Shard: {{shard}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(redpanda_kafka_handler_latency_seconds_bucket{handler=\"fetch\",instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m] offset 1d)) by (le, cluster))",
     "legendFormat": "Yesterday cluster avg"
    }
   ]
  },
  {
   "title": "Fetch Latency  (p99)",
   "type": "timeseries",
   "description": "Measured within Redpanda",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(redpanda_kafka_handler_latency_seconds_bucket{handler=\"fetch\",instance=~\"$node\",instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m])) by (le, [[aggr_criteria]]))",
     "legendFormat": "Pod: {{pod}}, Node: {{instance}}, Shard: {{shard}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(redpanda_kafka_handler_latency_seconds_bucket{handler=\"fetch\",instance=~\"$node\",instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m] offset 1d)) by (le, cluster))",
     "legendFormat": "Yesterday cluster avg"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 70 },
   "options": {
    "content": "<h1 style=\"color:#87CEEB; border-bottom: 3px solid #87CEEB;\">Internal RPC Latency</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 70 },
   "options": {
    "content": "<h1 style=\"color:#87CEEB; border-bottom: 3px solid #87CEEB;\">Throughput</h1>"
   }
  },
  {
   "title": "Internal RPC: Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(redpanda_rpc_request_latency_seconds_bucket{redpanda_server=\"internal\",instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m])) by (le, [[aggr_criteria]]))",
     "legendFormat": "Pod: {{pod}}, Node: {{instance}}, Shard: {{shard}}"
    }
   ]
  },
  {
   "title": "Internal RPC: Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(redpanda_rpc_request_latency_seconds_bucket{redpanda_server=\"internal\",instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m])) by (le, [[aggr_criteria]]))",
     "legendFormat": "Pod: {{pod}}, Node: {{instance}}, Shard: {{shard}}"
    }
   ]
  },
  {
   "title": "Rate - Total number of bytes read",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redpanda_kafka_request_bytes_total{redpanda_request=\"consume\", instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[5m])) by ([[aggr_criteria]])",
     "legendFormat": "pod: {{pod}}, node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Rate - Total number of bytes written",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redpanda_kafka_request_bytes_total{instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\",redpanda_request=\"produce\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[30s])) by ([[aggr_criteria]])",
     "legendFormat": "pod: {{pod}}, node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Under replicated partitions by topic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk by(redpanda_topic) (15, sum by(redpanda_topic, redpanda_namespace, redpanda_cloud_data_cluster_name) (redpanda_kafka_under_replicated_replicas{redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}!=0))",
     "legendFormat": "{{redpanda_topic}}/{{redpanda_namespace}}/{{redpanda_cloud_data_cluster_name}}"
    }
   ]
  },
  {
   "title": "Leaderless Partitions",
   "type": "table",
   "description": "\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(redpanda_namespace, redpanda_topic) (redpanda_kafka_partitions) - count by(redpanda_namespace, redpanda_topic) (count by (redpanda_namespace, redpanda_topic, redpanda_partition) (redpanda_kafka_under_replicated_replicas)!=0)!=0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization (Reactor)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by([[aggr_criteria]]) (deriv(redpanda_cpu_busy_seconds_total{instance=~\"[[node]]\", exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\", redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[$__rate_interval]))",
     "legendFormat": "Pod: {{pod}}, Node: {{instance}}, Shard: {{shard}}"
    },
    {
     "expr": "avg by([[aggr_criteria]]) (deriv(redpanda_cpu_busy_seconds_total{instance=~\"[[node]]\", exported_instance=~\"[[exported_node]]\",shard=~\"[[node_shard]]\", redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[$__rate_interval] offset 1d))",
     "legendFormat": "Yesterday cluster average"
    }
   ]
  },
  {
   "title": "Leadership Transfers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redpanda_raft_leadership_changes{redpanda_cloud_data_cluster_name=\"[[data_cluster]]\"}[5m])) by ([[aggr_criteria]])",
     "legendFormat": "Pod: {{pod}}, Node: {{instance}}"
    },
    {
     "expr": "sum(rate(redpanda_raft_leadership_changes{redpanda_cloud_data_cluster_name=\"[[data_cluster]]\"}[5m] offset 1d)) by (cluster)",
     "legendFormat": "Yesterday cluster avg"
    }
   ]
  },
  {
   "title": "Storage Saturation",
   "type": "timeseries",
   "description": "Available storage for Redpanda clusters",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(redpanda_storage_disk_free_bytes{instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}) by ([[aggr_criteria]])/sum(redpanda_storage_disk_total_bytes{instance=~\"[[node]]\",exported_instance=~\"[[exported_node]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}) by ([[aggr_criteria]])",
     "legendFormat": "Pod: {{pod}}, Node: {{instance}}"
    }
   ]
  }
 ]
}