{
 "title": "HELM / Pipelines",
 "tags": [ "helm" ],
 "time": { "from": "now-8h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Vessels Updated",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (interval) (vessels_updated)",
     "legendFormat": "{{ interval }}"
    }
   ]
  },
  {
   "title": "AIS Updated",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (source, interval) (ais_updated)",
     "legendFormat": "{{ source }} {{ interval }}"
    }
   ]
  },
  {
   "title": "AIS Archive Updated",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (source, interval) (ais_archive_updated)",
     "legendFormat": "{{ source }} {{ interval }}"
    }
   ]
  },
  {
   "title": "AIS Type 5 Archive Updated",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (source, interval) (ais_type5_archive_updated)",
     "legendFormat": "{{ source }} {{ interval }}"
    }
   ]
  },
  {
   "title": "Events Updated",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (event, interval) (events_updated)",
     "legendFormat": "{{ event }} {{ interval }}"
    }
   ]
  },
  {
   "title": "Aggregations Updated",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (aggregation, interval) (aggregations_updated)",
     "legendFormat": "{{ aggregation }} {{ interval }}"
    }
   ]
  },
  {
   "title": "Events count by zone type",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (zone) (zone_events_count)",
     "legendFormat": "{{ zone }}"
    }
   ]
  },
  {
   "title": "Events count by event type",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (event) (ais_events_count)",
     "legendFormat": "{{ zone }}"
    }
   ]
  }
 ]
}