{
 "title": "HELM / Pipelines (jdang)",
 "tags": [ "helm" ],
 "time": { "from": "now-8h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Vessels Updated",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (interval) (vessels_updated)",
     "legendFormat": "{{ interval }}"
    }
   ]
  },
  {
   "title": "Ais Raw Feeds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (source, interval) (ais_updated)",
     "legendFormat": "{{ source }} {{ interval }}"
    }
   ]
  },
  {
   "title": "Ais Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (event, interval) (events_updated)",
     "legendFormat": "{{ event }} {{ interval }}"
    }
   ]
  },
  {
   "title": "Ais Archive Updated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (source, interval) (ais_archive_updated)",
     "legendFormat": "{{ source }} {{ interval }}"
    }
   ]
  },
  {
   "title": "Aggregations Updated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by (aggregation, interval) (aggregations_updated)",
     "legendFormat": "{{ aggregation }} {{ interval }}"
    }
   ]
  },
  {
   "title": "AIS Type 5 Archive Updated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "max by (source, interval) (ais_type5_archive_updated)",
     "legendFormat": "{{ source }} {{ interval }}"
    }
   ]
  },
  {
   "title": "Events count by event type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max by (event) (ais_events_count)",
     "legendFormat": "{{ zone }}"
    }
   ]
  },
  {
   "title": "Events count by zone type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "max by (zone) (zone_events_count)",
     "legendFormat": "{{ zone }}"
    }
   ]
  }
 ]
}