{
 "title": "HELM / Pipelines Vessel Position",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "action",
    "query": {
     "query": "label_values(http_requests_received_total, action)"
    }
   },
   {
    "name": "code",
    "query": {
     "query": "label_values(http_requests_received_total, code)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(http_requests_received_total,host)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(http_requests_received_total,method)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align:center;color:#3399ff;font-size: 50px\"><b>VESSEL POSITION DASHBOARD</b></h1>"
   }
  },
  {
   "title": "Total Requests (Period)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{ code=~\"$code\", action=~\"$action\", host=~\"$host\", method=~\"$method\"}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": " Success Rate (non-4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{ code!~\"[4-5].*\"}[${__range_s}s])) / sum(rate(http_requests_received_total{}[${__range_s}s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System net sockets received",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_net_sockets_bytes_received"
    }
   ]
  },
  {
   "title": "System net sockets sent",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_net_sockets_bytes_sent" }
   ]
  },
  {
   "title": "Total Requests (Increase)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{ code=~\"$code\", action=~\"$action\", host=~\"$host\", method=~\"$method\"}[1m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Total Requests (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{ code=~\"$code\", action=~\"$action\", host=~\"$host\", method=~\"$method\"}[1m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "System net sockets outgoing connections established",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(system_net_sockets_outgoing_connections_established[$__interval])",
     "legendFormat": "Connections-established"
    }
   ]
  },
  {
   "title": "Vessel Position Request Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"$code\",action=~\"$action\",host=~\"$host\"}[1m])) by (code, action)",
     "legendFormat": "{{action}}-{{code}}"
    }
   ]
  },
  {
   "title": "Vessel Position Request Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"$code\",host=~\"$host\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Vessel Position Request Action Types",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"$code\",method=~\"$method\",host=~\"$host\",action=~\"$action\",host=~\"$host\"}[1m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Percentile Response Times (LineChart)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{host=~\"$host\",action=~\"$action\"}[$__interval])) by (le, host, action))",
     "legendFormat": "P50-{{action}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{host=~\"$host\",action=~\"$action\"}[$__interval])) by (le, host, action))",
     "legendFormat": "P90-{{action}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{host=~\"$host\",action=~\"$action\"}[$__interval])) by (le, host, action))",
     "legendFormat": "P99-{{action}}"
    }
   ]
  },
  {
   "title": "Http requests in progress (rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_in_progress{ action=~\"$action\", host=~\"$host\"}[1m])) by (action)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "System net sockets outgoing connections established",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "system_net_sockets_outgoing_connections_established",
     "legendFormat": "Requests - {{action}}"
    }
   ]
  },
  {
   "title": "Http requests in progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{ action=~\"$action\", host=~\"$host\"}) by (action)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "System net sockets outgoing connections established",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_in_progress{ action=~\"$action\"}[1m])) by (action)",
     "legendFormat": "Requests - {{action}}"
    }
   ]
  },
  {
   "title": "Percentile Response Times (Table)",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{host=~\"$host\",action=~\"$action\"}[$__interval])) by (le, host))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{host=~\"$host\",action=~\"$action\"}[$__interval])) by (le, host))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{host=~\"$host\",action=~\"$action\"}[$__interval])) by (le, host))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}