{
 "title": "HELM / Pod Resources Change",
 "tags": [ "helm" ],
 "time": { "from": "now-8h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "POD CPU Change >  10% (1 day delta)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate[2h]) / avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate[2h] offset 1d) - 1) > 0.1",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    },
    {
     "expr": "(avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate[2h]) / avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate[2h] offset 1d) - 1) < -0.1",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    }
   ]
  },
  {
   "title": "POD CPU Change >  10% (1 week delta)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate[2h]) / avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate[2h] offset 1w) - 1) > 0.1",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    },
    {
     "expr": "(avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate[2h]) / avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate[2h] offset 1w) - 1) < -0.1",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    }
   ]
  },
  {
   "title": "POD Memory Change > 10% (1 day delta)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(node_namespace_pod_container:container_memory_rss[2h]) / avg_over_time(node_namespace_pod_container:container_memory_rss[2h] offset 1d) - 1) > 0.1",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    },
    {
     "expr": "(avg_over_time(node_namespace_pod_container:container_memory_rss[2h]) / avg_over_time(node_namespace_pod_container:container_memory_rss[2h] offset 1d) - 1) < -0.1",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    }
   ]
  },
  {
   "title": "POD Memory Change > 10% (1 week delta)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(node_namespace_pod_container:container_memory_rss[2h]) / avg_over_time(node_namespace_pod_container:container_memory_rss[2h] offset 1w) - 1) > 0.1",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    },
    {
     "expr": "(avg_over_time(node_namespace_pod_container:container_memory_rss[2h]) / avg_over_time(node_namespace_pod_container:container_memory_rss[2h] offset 1w) - 1) < -0.1",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    }
   ]
  }
 ]
}