{
 "title": "Connectors",
 "description": "Connectors dashboard",
 "tags": [ "connectors" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "connector",
    "query": {
     "query": "label_values(kafka_connect_connector_task_running_ratio,connector)"
    }
   },
   {
    "name": "task",
    "query": {
     "query": "label_values(kafka_connect_connector_task_running_ratio{connector=~\"$connector\"},task)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connector tasks for [[connector]]",
   "type": "timeseries",
   "description": "Number of all tasks of all connectors. Expect to see only running and paused connectors.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "repeat": "connector",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (kafka_connect_connector_status{connector=~\"[[connector]]\", task=~\"[[task]]\", status=\"running\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum (kafka_connect_connector_status{connector=~\"[[connector]]\", task=~\"[[task]]\", status=\"paused\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum (kafka_connect_connector_status{connector=~\"[[connector]]\", task=~\"[[task]]\", status=\"failed\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum (kafka_connect_connector_status{connector=~\"[[connector]]\", task=~\"[[task]]\", status=\"unassigned\"})",
     "legendFormat": "unassigned"
    },
    {
     "expr": "sum (kafka_connect_connector_status{connector=~\"[[connector]]\", task=~\"[[task]]\", status=\"destroyed\"})",
     "legendFormat": "destroyed"
    },
    {
     "expr": "sum (kafka_connect_connector_status{connector=~\"[[connector]]\", task=~\"[[task]]\", status=\"restarting\"})",
     "legendFormat": "restarting"
    }
   ]
  },
  {
   "title": "Sink connector lag",
   "type": "timeseries",
   "description": "Sink connector lag counted in a number of records",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lag_avg{clientId=~\"connector-consumer-[[connector]]-[[task]]\"}",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "Sink connector lag rate",
   "type": "timeseries",
   "description": "Sink connector lag rate. Should be negative from time to time, otherwise the sink connector is not making progress.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "sum by(connector, redpanda_topic)(max by(redpanda_topic, redpanda_partition)(rate(redpanda_kafka_max_offset{redpanda_namespace=\"kafka\"}[5m])) - on(redpanda_topic, redpanda_partition) group_right max by(connector, redpanda_topic, redpanda_partition)(label_replace(rate(redpanda_kafka_consumer_group_committed_offset{redpanda_group=~\"connect-[[connector]]\"}[5m]),\"connector\", \"$1\", \"redpanda_group\", \"connect-(.*)\")))",
     "legendFormat": "{{connector}} {{redpanda_topic}}"
    }
   ]
  },
  {
   "title": "MM2 replication latency",
   "type": "timeseries",
   "description": "MM2 replication lag counted in ms",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_mirror_source_connector_replication_latency_ms_max",
     "legendFormat": "{{topic}} {{partition}}"
    }
   ]
  },
  {
   "title": "Count of the records sent to target (by topic)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_producer_topic_record_send_total{clientId=~\"connector-producer-[[connector]]-.*\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Redpanda consumer latency",
   "type": "timeseries",
   "description": "Redpanda latency for sink connectors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_avg{clientId=~\"connector-consumer-[[connector]]-[[task]]\"}",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "Redpanda producer latency",
   "type": "timeseries",
   "description": "Redpanda latency for source connectors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "kafka_connector_producer_request_latency_avg{connector=~\"[[connector]]\", task=~\"[[task]]\"}",
     "legendFormat": "{{connector}} {{task}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Bytes in",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_consumer_node_incoming_byte_total{clientId=~\"connector-consumer-[[connector]]-[[task]]\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_producer_node_outgoing_byte_total{clientId=~\"connector-producer-[[connector]]-[[task]]\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Record rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Record error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum (rate(kafka_connect_task_error_total_record_errors{connector=~\".*[[connector]]\", task=~\"[[task]]\"}[5m]))",
     "legendFormat": "record errors"
    },
    {
     "expr": "sum (rate(kafka_connect_task_error_total_record_failures{connector=~\".*[[connector]]\", task=~\"[[task]]\"}[5m]))",
     "legendFormat": "record failures"
    },
    {
     "expr": "sum (rate(kafka_connect_task_error_total_records_skipped{connector=~\".*[[connector]]\", task=~\"[[task]]\"}[5m]))",
     "legendFormat": "record skipped"
    }
   ]
  },
  {
   "title": "Producer record rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum (rate(kafka_connector_producer_record_send_total{connector=~\"[[connector]]\", task=~\"[[task]]\"}[5m]))",
     "legendFormat": "record send"
    },
    {
     "expr": "sum (rate(kafka_connector_producer_record_retry_total{connector=~\"[[connector]]\", task=~\"[[task]]\"}[5m]))",
     "legendFormat": "record retry"
    }
   ]
  },
  {
   "title": "Producer record error rate",
   "type": "timeseries",
   "description": "Failures in producing to Redpanda",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 60 },
   "targets": [
    {
     "expr": "sum (rate(kafka_producer_record_error_total[5m]))",
     "legendFormat": "producer error rate"
    }
   ]
  }
 ]
}