{
 "title": "Kafka Java Consumer",
 "description": "Kafka Consumer Java client metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "client_id",
    "label": "Client ID",
    "query": {
     "query": "label_values(kafka_consumer_app_info_starttimems,id)"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(kafka_producer_producer_topic_metrics_record_send_total,topic)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_consumer_app_info_starttimems,instance)"
    }
   },
   {
    "name": "aggr_criteria",
    "label": "Aggregate By",
    "query": "cluster,client_id,client_id\\,instance,instance"
   },
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Note\nThis dashboard requires a JMX agent reporting statistics from a Kafka Java consumer into Prometheus."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Key metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Commit rate",
   "type": "timeseries",
   "description": "The number of commit calls per second .",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_consumer_coordinator_metrics_commit_rate{client_id=~'[[client_id]]',instance=~'[[instance]]'} )"
    }
   ]
  },
  {
   "title": "Average fetch throttle time",
   "type": "stat",
   "description": "The average time in ms a request was throttled by a broker.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_produce_throttle_time_avg"
    }
   ]
  },
  {
   "title": "Failed auth rate",
   "type": "stat",
   "description": "Rate of failed authentication attempts\n",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_admin_client_admin_client_metrics_failed_authentication_rate{instance=~'[[instance]]'}"
    }
   ]
  },
  {
   "title": "Rebalance rate per hour",
   "type": "timeseries",
   "description": "The number of total rebalance events per hour, both successful and unsuccessful rebalance attempts.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_consumer_coordinator_metrics_rebalance_rate_per_hour{client_id=~'[[client_id]]'}) by ([[aggr_criteria]])",
     "legendFormat": "{{client_id}} {{instance}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "process_cpu_seconds_total  " }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max) by (area, [[aggr_criteria]])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM GC time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(jvm_gc_collection_seconds_sum[5m])) by (gc,[[aggr_criteria]])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bytes consumed rate",
   "type": "timeseries",
   "description": "The average number of bytes consumed per second\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total{client_id=~'[[client_id]]',instance=~'[[instance]]',topic=~'[[topic]]'}[1m])) by ([[aggr_criteria]])",
     "legendFormat": "{{client_id}} {{instance}} {{topic}}"
    }
   ]
  },
  {
   "title": "Rate of records consumed",
   "type": "timeseries",
   "description": "The average number of records consumed per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_total{client_id=~'[[client_id]]',instance=~'[[instance]]',topic=~'[[topic]]'}[1m])) by ([[aggr_criteria]])",
     "legendFormat": "{{client_id}} {{instance}} {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes consumed rate per topic",
   "type": "timeseries",
   "description": "The average number of bytes consumed per topic per second.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total{client_id=~'[[client_id]]',instance=~'[[instance]]',topic=~'[[topic]]'}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Rate of records consumed per topic",
   "type": "timeseries",
   "description": "The average number of records consumed per second per topic.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{client_id=~'[[client_id]]',instance=~'[[instance]]',topic=~'[[topic]]'}[1m]))by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Fetch Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fetch request rate",
   "type": "timeseries",
   "description": "The number of fetch requests per second.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_consumer_fetch_manager_metrics_fetch_rate) by ([[aggr_criteria]])",
     "legendFormat": "Request Rate {{instance}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Fetch size",
   "type": "timeseries",
   "description": "The number of bytes fetched per request for a topic",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_consumer_fetch_manager_metrics_fetch_size_avg) by ([[aggr_criteria]])",
     "legendFormat": "Average {{instance}} {{client_id}}"
    },
    {
     "expr": "max(kafka_consumer_consumer_fetch_manager_metrics_fetch_size_max) by ([[aggr_criteria]])",
     "legendFormat": "Max {{instance}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Fetch latency average",
   "type": "timeseries",
   "description": "The average time taken for a fetch request.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_avg) by ([[aggr_criteria]])",
     "legendFormat": "Average {{instance}} {{client_id}}"
    },
    {
     "expr": "max(kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_max) by ([[aggr_criteria]])",
     "legendFormat": "Max {{instance}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Consumer Commit Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Commit latency average",
   "type": "timeseries",
   "description": "The average time taken for a commit request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_consumer_coordinator_metrics_commit_latency_avg) by ([[aggr_criteria]])",
     "legendFormat": "Average {{instance}} {{client_id}}"
    },
    {
     "expr": "max(kafka_consumer_consumer_coordinator_metrics_commit_latency_max) by ([[aggr_criteria]])",
     "legendFormat": "Max {{instance}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Commit rate",
   "type": "timeseries",
   "description": "The number of commit calls per second .",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_consumer_coordinator_metrics_commit_rate) by ([[aggr_criteria]])",
     "legendFormat": "{{instance}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current connection count",
   "type": "timeseries",
   "description": "Number of simultaneous connections\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_consumer_metrics_connection_count{instance=~'[[instance]]', client_id=~'[[client_id]]'}) by ([[aggr_criteria]])",
     "legendFormat": "{{instance}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Node reponse rate",
   "type": "timeseries",
   "description": "response rate per node\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_consumer_node_metrics_response_rate{instance=~'[[instance]]', client_id=~'[[client_id]]'}) by ([[aggr_criteria]])",
     "legendFormat": "{{instance}} {{client_id}}"
    }
   ]
  }
 ]
}