{
 "title": "Kafka Java Producer",
 "description": "Kafka Producer Java client metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "client_id",
    "label": "Client ID",
    "query": {
     "query": "label_values(kafka_producer_app_info_starttimems,id)"
    }
   },
   { "name": "topic", "label": "topic", "query": { "query": "label_values(topic)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_producer_app_info_start_time_ms,instance)"
    }
   },
   {
    "name": "aggr_criteria",
    "label": "Aggregate By",
    "query": "cluster,client_id,client_id\\,instance,instance"
   },
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Note\nThis dashboard requires a JMX agent reporting statistics from a Kafka Java producer into Prometheus.\n\n⚠️ This dashboard has some sample thresholds, this example is not meant to fit all use cases nor is it meant for production. Think of it as a learning tool to help you become comfortable with the metrics and thresholding.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Key metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Produce rate",
   "type": "timeseries",
   "description": "The number of bytes produced",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(kafka_producer_producer_topic_metrics_byte_rate{client_id=~'[[client_id]]',instance=~'[[instance]]',topic=~'[[topic]]'})  ",
     "legendFormat": "Produce Rate"
    }
   ]
  },
  {
   "title": "Average produce throttle time",
   "type": "stat",
   "description": "The average time in ms a request was throttled by a broker.",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_produce_throttle_time_avg "
    }
   ]
  },
  {
   "title": "Failed auth rate",
   "type": "stat",
   "description": "Rate of failed authentication attempts\n",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_admin_client_admin_client_metrics_failed_authentication_rate{instance=~'[[instance]]'}"
    }
   ]
  },
  {
   "title": "Producer Error Rate",
   "type": "timeseries",
   "description": "Producer error rate",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_producer_producer_metrics_record_error_rate)",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Average Compression Rate",
   "type": "timeseries",
   "description": "Average compression rate across all producers",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_producer_metrics_compression_rate_avg{client_id=~\"[[client_id]]\",instance=~\"[[instance]]\"})",
     "legendFormat": "{{client_id}} {{instance}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_cpu_seconds_total  " }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max) by (area, [[aggr_criteria]])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM GC time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(jvm_gc_collection_seconds_sum[5m])) by (gc,[[aggr_criteria]])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bytes produced rate",
   "type": "timeseries",
   "description": "The average number of bytes produced per second\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_producer_topic_metrics_byte_total{client_id=~'[[client_id]]',instance=~'[[instance]]',topic=~'[[topic]]'}[1m])) by ([[aggr_criteria]])",
     "legendFormat": "{{client_id}} {{instance}} {{topic}}"
    }
   ]
  },
  {
   "title": "Rate of records produced",
   "type": "timeseries",
   "description": "The average number of records produced per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_producer_topic_metrics_record_send_total{client_id=~'[[client_id]]',instance=~'[[instance]]',topic=~'[[topic]]'}[1m])) by ([[aggr_criteria]])",
     "legendFormat": "{{client_id}} {{instance}} {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes produced rate per topic",
   "type": "timeseries",
   "description": "The average number of bytes produced per topic per second.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_producer_topic_metrics_byte_total{client_id=~'[[client_id]]',instance=~'[[instance]]',topic=~'[[topic]]'}[1m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of records produced per topic",
   "type": "timeseries",
   "description": "The average number of records produced per second per topic.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_producer_topic_metrics_record_send_total{client_id=~'[[client_id]]',instance=~'[[instance]]',topic=~'[[topic]]'}[1m]))by (topic)"
    }
   ]
  },
  {
   "title": "Producer Batch Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Produce request rate",
   "type": "timeseries",
   "description": "The number of produce requests per second.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_producer_producer_node_metrics_request_rate) by ([[aggr_criteria]])",
     "legendFormat": "Request Rate {{instance}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Produce batch size",
   "type": "timeseries",
   "description": "Batch sizes produced",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_producer_metrics_batch_size_avg) by ([[aggr_criteria]])",
     "legendFormat": "Average {{instance}} {{client_id}}"
    },
    {
     "expr": " max(kafka_producer_producer_metrics_batch_size_max) by ([[aggr_criteria]])",
     "legendFormat": "Max {{instance}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Produce latency",
   "type": "timeseries",
   "description": "The average time taken for a produce request.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_producer_metrics_request_latency_avg) by ([[aggr_criteria]])",
     "legendFormat": "Average {{instance}} {{client_id}}"
    },
    {
     "expr": "max(kafka_producer_producer_metrics_request_latency_max) by ([[aggr_criteria]])",
     "legendFormat": "Max {{instance}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current connection count",
   "type": "timeseries",
   "description": "Number of simultaneous connections\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_producer_producer_metrics_connection_count{instance=~'[[instance]]'}) by ([[aggr_criteria]])",
     "legendFormat": "{{instance}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Node reponse rate",
   "type": "timeseries",
   "description": "response rate per node\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_producer_producer_metrics_response_rate{instance=~'[[instance]]'}) by ([[aggr_criteria]])",
     "legendFormat": "{{instance}} {{client_id}}"
    }
   ]
  }
 ]
}