{
 "title": "HELM / PostgreSQL",
 "tags": [ "helm" ],
 "time": { "from": "now-8h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "service", "query": { "query": "label_values(pg_up, service)" } },
   {
    "name": "exclude_databases",
    "query": "postgres|template0|template1|defaultdb|_aiven"
   }
  ]
 },
 "panels": [
  {
   "title": "$service: Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "repeat": "service",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (short_version) (pg_static{service=\"$service\"})",
     "legendFormat": "{{ short_version }}"
    }
   ]
  },
  {
   "title": "$service: Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (datname) (pg_database_size_bytes{service=\"$service\", datname!~\"|$exclude_databases\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "$service: Backends",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "repeat": "service",
   "targets": [
    {
     "expr": "max_over_time(pg_stat_database_numbackends{service=\"$service\", datname!~\"|$exclude_databases\"}[5m])",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "$service: Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "repeat": "service",
   "targets": [
    {
     "expr": "sum(max_over_time(pg_stat_activity_count{service=\"$service\", datname!~\"|$exclude_databases\"}[5m])) by (datname, state)",
     "legendFormat": "{{ datname }}: {{ state }}"
    }
   ]
  },
  {
   "title": "$service: Max Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(pg_stat_activity_max_tx_duration{service=\"$service\", datname!~\"|$exclude_databases\"}[5m])",
     "legendFormat": "{{datname}}: {{ state }}"
    }
   ]
  },
  {
   "title": "$service: Locks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "repeat": "service",
   "targets": [
    {
     "expr": "max_over_time(pg_locks_count{service=\"$service\", datname!~\"|$exclude_databases\"}[5m])",
     "legendFormat": "{{ datname }}: {{ mode }}"
    }
   ]
  },
  {
   "title": "$service: Cache Hit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{service=\"$service\", datname!~\"|$exclude_databases\"}) by (datname) /\n(sum(pg_stat_database_blks_hit{service=\"$service\", datname!~\"|$exclude_databases\"}) by (datname) + \nsum(pg_stat_database_blks_read{service=\"$service\", datname!~\"|$exclude_databases\"}) by (datname))",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "$service: Temp Files",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "repeat": "service",
   "targets": [
    {
     "expr": "max_over_time(pg_stat_database_temp_files{service=\"$service\", datname!~\"|$exclude_databases\"}[5m])",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "$service: Temp Files Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(pg_stat_database_temp_bytes{service=\"$service\", datname!~\"|$exclude_databases\"}[5m])",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "$service: Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(pg_scrape_collector_duration_seconds{service=\"$service\"}[5m])",
     "legendFormat": "{{ collector }}"
    },
    {
     "expr": "max_over_time(pg_exporter_last_scrape_duration_seconds{service=\"$service\"}[5m])",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "$service: Settings",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "topk(100, {__name__=~\"pg_settings_.*\", service=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}