{
 "title": "HELM / Certificates",
 "tags": [ "helm" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes Certificates",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(x509_cert_not_after{secret_namespace=~\"$namespace\"} - time()) / 86400"
    }
   ]
  },
  {
   "title": "External Certificates",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(ssl_cert_expiry_time - time()) / 86400"
    }
   ]
  },
  {
   "title": "Exporter errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(x509_read_errors)", "legendFormat": "errors" }
   ]
  }
 ]
}