{
 "title": "HELM / Quarkus",
 "tags": [ "helm" ],
 "time": { "from": "now-8h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(process_uptime_seconds, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(process_uptime_seconds{namespace=\"$namespace\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$service Information",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "repeat": "service",
   "targets": [
    {
     "expr": "max by (namespace, pod, runtime, vendor, version) (jvm_info_total{namespace=\"$namespace\", service=\"$service\"})"
    },
    {
     "expr": "max by (pod) (system_cpu_count{namespace=\"$namespace\", service=\"$service\"})"
    }
   ]
  },
  {
   "title": "$service Uptime",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "repeat": "service",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (service) (process_uptime_seconds{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "$service Request Duration (Max)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
   "repeat": "service",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (method, uri, status) (http_server_requests_seconds_max{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "{{ method }} {{ uri }} {{ status }}"
    }
   ]
  },
  {
   "title": "$service Requests Duration (Average)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "repeat": "service",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (method, uri, status) (http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"$service\"} / http_server_requests_seconds_count)",
     "legendFormat": "{{ method }} {{ uri }} {{ status }}"
    }
   ]
  },
  {
   "title": "$service Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "repeat": "service",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (area, id) (jvm_memory_max_bytes{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "max: {{ area }} / {{ id }}"
    },
    {
     "expr": "max by (area, id) (jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "used: {{ area }} / {{ id }}"
    },
    {
     "expr": "max by (area, id) (jvm_memory_committed_bytes{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "committed: {{ area }} / {{ id }}"
    },
    {
     "expr": "max by (id) (jvm_buffer_memory_used_bytes{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "buffer_used: {{ id }}"
    },
    {
     "expr": "max by (id) (jvm_buffer_total_capacity_bytes{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "buffer_capacity: {{ id }}"
    }
   ]
  },
  {
   "title": "$service CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
   "repeat": "service",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (service) (system_cpu_usage{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "max by (service) (process_cpu_usage{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "$service Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 90 },
   "repeat": "service",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (service) (system_load_average_1m{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "1m"
    }
   ]
  },
  {
   "title": "$service File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 108 },
   "repeat": "service",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (service) (process_files_open_files{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "open_files"
    }
   ]
  },
  {
   "title": "$service JVM Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 126 },
   "repeat": "service",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (state) (jvm_threads_states_threads{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "max by (service) (jvm_threads_live_threads{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "live"
    },
    {
     "expr": "max by (service) (jvm_threads_daemon_threads{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "$service JVM GC Overhead",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 144 },
   "repeat": "service",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (service) (jvm_gc_overhead_percent{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "jvm_gc_overhead"
    }
   ]
  },
  {
   "title": "$service JVM GC Pause Time (Max)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 162 },
   "repeat": "service",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (cause, action) (jvm_gc_pause_seconds_max{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "{{ cause }}: {{ action }}"
    }
   ]
  }
 ]
}