{
 "title": "HELM / Elasticsearch",
 "tags": [ "helm" ],
 "time": { "from": "now-8h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_status,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Data Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_data_nodes{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_active_shards{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active Primary Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_active_primary_shards{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_initializing_shards{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_relocating_shards{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_unassigned_shards{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Delayed Unassigned Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_delayed_unassigned_shards{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_pending_tasks{cluster=~\"$cluster\"})"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Indices Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(elasticsearch_indices_store_size_bytes_total{cluster=~\"$cluster\"}) by (cluster, index)",
     "legendFormat": "{{ index }}"
    }
   ]
  },
  {
   "title": "Indices Documents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_indices_docs_total{cluster=~\"$cluster\"}) by (cluster, index)",
     "legendFormat": "{{ index }}"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(irate(elasticsearch_indices_search_fetch_total{cluster=~\"$cluster\"}[1h])) by (cluster)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indexing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(irate(elasticsearch_indices_indexing_index_total{cluster=~\"$cluster\"}[1h])) by (cluster)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_thread_pool_queue_count{cluster=~\"$cluster\"}) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pools",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_thread_pool_active_count{cluster=~\"$cluster\", type!=\"management\"}) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "JVM Heap Memory (average in 30m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(avg_over_time(elasticsearch_jvm_memory_used_bytes{area=\"heap\",cluster=~\"$cluster\"}[30m]) / elasticsearch_jvm_memory_max_bytes{area=\"heap\",cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}