{
 "title": "HELM / AIS Ingestion Monitoring",
 "tags": [ "helm" ],
 "time": { "from": "now-8h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align:center;color:#3399ff;font-size: 50px\"><b>AIS INGESTION MONITORING DASHBOARD</b></h1>"
   }
  },
  {
   "title": "Total Vessels Updated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (interval) (vessels_updated)",
     "legendFormat": "{{ interval }}"
    }
   ]
  },
  {
   "title": "Vessels Updated by Vendor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (source, interval) (ais_updated)",
     "legendFormat": "{{ source }} {{ interval }}"
    }
   ]
  },
  {
   "title": "Events Updated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (event, interval) (events_updated)",
     "legendFormat": "{{ event }} {{ interval }}"
    }
   ]
  },
  {
   "title": "Events Aggregation Updated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (aggregation, interval) (aggregations_updated)",
     "legendFormat": "{{ aggregation }} {{ interval }}"
    }
   ]
  },
  {
   "title": "Events by Zone Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (zone) (zone_events_count)",
     "legendFormat": "{{ zone }}"
    }
   ]
  },
  {
   "title": "Events by Event Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (event) (ais_events_count)",
     "legendFormat": "{{ zone }}"
    }
   ]
  }
 ]
}