{
 "title": "HELM / Kafka",
 "tags": [ "helm" ],
 "time": { "from": "now-8h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(kafka_consumergroup_poll_time_ms, cluster_name)"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(kafka_consumergroup_group_offset,topic)"
    }
   },
   {
    "name": "group",
    "label": "group",
    "query": {
     "query": "label_values(kafka_consumergroup_group_offset,group)"
    }
   },
   {
    "name": "partition",
    "label": "partition",
    "query": {
     "query": "label_values(kafka_consumergroup_group_offset,partition)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$service Group MAX Lag (Time)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(kafka_consumergroup_group_max_lag_seconds{cluster_name=\"$service\"} >= 0) by (group)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "$service Group MAX Lag (Offset)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(kafka_consumergroup_group_max_lag{cluster_name=\"$service\"} >= 0) by (group)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "$service Group SUM Lag (Offset)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(kafka_consumergroup_group_sum_lag{cluster_name=\"$service\"} >= 0) by (group)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "$service Group Topic SUM Lag (Offset)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(kafka_consumergroup_group_topic_sum_lag{cluster_name=\"$service\"} >= 0) by (group, topic)",
     "legendFormat": "{{group}} / {{topic}}"
    }
   ]
  },
  {
   "title": "$service Poll Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(kafka_consumergroup_poll_time_ms{cluster_name=\"$service\"} >= 0) by (cluster_name)",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  }
 ]
}