{
 "title": "HELM / Nodes",
 "tags": [ "helm" ],
 "time": { "from": "now-8h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=\"node-exporter\"}, instance)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_last_seen{namespace=\"$namespace\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "[[instance]] Status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (instance, nodename) (node_uname_info{instance=~\"[[instance]].*\"})",
     "legendFormat": "{{ nodename }}"
    },
    {
     "expr": "kube_node_status_condition{status=\"true\"} * on(node) group_left(internal_ip) max by (internal_ip, node) (kube_node_info{internal_ip=~\"[[instance]].*\"}) > 0",
     "legendFormat": "{{ condition }}"
    },
    {
     "expr": "kube_node_role * on(node) group_left(internal_ip) max by (internal_ip, node) (kube_node_info{internal_ip=~\"[[instance]].*\"})",
     "legendFormat": "{{ role }}"
    },
    {
     "expr": "kube_node_spec_taint * on(node) group_left(internal_ip) max by (internal_ip, node) (kube_node_info{internal_ip=~\"[[instance]].*\"})",
     "legendFormat": "{{ key }}"
    }
   ]
  },
  {
   "title": "[[instance]] Capacity",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "kube_node_status_capacity{resource=\"cpu\"} * on(node) group_left(internal_ip) max by (internal_ip, node) (kube_node_info{internal_ip=~\"[[instance]].*\"})",
     "legendFormat": "CPU (cores)"
    },
    {
     "expr": "kube_node_status_capacity{resource=\"memory\"} / 1024^3 * on(node) group_left(internal_ip) max by (internal_ip, node) (kube_node_info{internal_ip=~\"[[instance]].*\"})",
     "legendFormat": "Memory (GiB)"
    },
    {
     "expr": "kube_node_status_capacity{resource=\"ephemeral_storage\"} / 1024^3 * on(node) group_left(internal_ip) max by (internal_ip, node) (kube_node_info{internal_ip=~\"[[instance]].*\"})",
     "legendFormat": "Storage (GiB)"
    },
    {
     "expr": "kube_node_status_capacity{resource=\"pods\"} * on(node) group_left(internal_ip) max by (internal_ip, node) (kube_node_info{internal_ip=~\"[[instance]].*\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "[[instance]] CPU",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, mode) (irate(node_cpu_seconds_total{instance=~\"[[instance]].*\"}[5m])) / count by (instance, mode) (node_cpu_seconds_total)",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "[[instance]] LA",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (instance) (node_load1{instance=~\"[[instance]].*\"})",
     "legendFormat": "LA 1"
    },
    {
     "expr": "max by (instance) (node_load5{instance=~\"[[instance]].*\"})",
     "legendFormat": "LA 5"
    },
    {
     "expr": "max by (instance) (node_load15{instance=~\"[[instance]].*\"})",
     "legendFormat": "LA 15"
    },
    {
     "expr": "machine_cpu_cores{instance=~\"[[instance]].*\"}",
     "legendFormat": "LIMIT"
    }
   ]
  },
  {
   "title": "[[instance]] Memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "repeat": "instance",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max by (instance) (node_memory_MemFree_bytes{instance=~\"[[instance]].*\"})",
     "legendFormat": "free"
    },
    {
     "expr": "max by (instance) (node_memory_Buffers_bytes{instance=~\"[[instance]].*\"})",
     "legendFormat": "buffers"
    },
    {
     "expr": "max by (instance) (node_memory_Cached_bytes{instance=~\"[[instance]].*\"})",
     "legendFormat": "cached"
    },
    {
     "expr": "max by (instance) (node_memory_MemTotal_bytes{instance=~\"[[instance]].*\"} - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_MemFree_bytes)",
     "legendFormat": "used"
    },
    {
     "expr": "max by (instance) (node_memory_Shmem_bytes{instance=~\"[[instance]].*\"})",
     "legendFormat": "SHARED"
    },
    {
     "expr": "max by (instance) (node_memory_MemAvailable_bytes{instance=~\"[[instance]].*\"})",
     "legendFormat": "AVAILABLE"
    }
   ]
  },
  {
   "title": "[[instance]] Disk Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(1 - node_filesystem_avail_bytes{instance=~\"[[instance]].*\", fstype!~\"tmpfs|.*lxcfs\"} / node_filesystem_size_bytes) by (instance, mountpoint, device)",
     "legendFormat": "{{ mountpoint }} ({{ device }})"
    },
    { "expr": "0.85", "legendFormat": "LIMIT" }
   ]
  },
  {
   "title": "[[instance]] Disk IO",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 25 },
   "repeat": "instance",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max by (instance) (irate(node_disk_reads_completed_total{instance=~\"[[instance]].*\",device=~\"sd.*\"}[5m]))",
     "legendFormat": "{{ device }} reads"
    },
    {
     "expr": "min by (instance) (-irate(node_disk_writes_completed_total{instance=~\"[[instance]].*\",device=~\"sd.*\"}[5m]))",
     "legendFormat": "{{ device }} writes"
    }
   ]
  },
  {
   "title": "[[instance]] Network",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 29 },
   "repeat": "instance",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "max by (instance) (irate(node_network_transmit_bytes_total{instance=~\"[[instance]].*\",device=~\"eth.*\"}[5m]))",
     "legendFormat": "{{ device }} transmit"
    },
    {
     "expr": "min by (instance) (irate(node_network_receive_bytes_total{instance=~\"[[instance]].*\",device=~\"eth.*\"}[5m]))",
     "legendFormat": "{{ device }} receive"
    }
   ]
  },
  {
   "title": "[[instance]] Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 33 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (instance) (node_netstat_Tcp_CurrEstab{instance=~\"[[instance]].*\"})",
     "legendFormat": "Established"
    }
   ]
  },
  {
   "title": "[[instance]] Pods",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 37 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (instance) (kubelet_running_pods{instance=~\"[[instance]].*\"})",
     "legendFormat": "pods"
    },
    {
     "expr": "kube_node_status_capacity{resource=\"pods\"} * on(node) group_left(internal_ip) max by (internal_ip, node) (kube_node_info{internal_ip=~\"[[instance]].*\"})",
     "legendFormat": "LIMIT"
    }
   ]
  },
  {
   "title": "[[instance]] Pod CPU",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 41 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{instance=~\"[[instance]].*\",namespace=~\"[[namespace]]\",container=~\"[[container]]\",container!=\"\"}[5m])) by (namespace, pod, container)",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    }
   ]
  },
  {
   "title": "[[instance]] Pod Memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 45 },
   "repeat": "instance",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (namespace, pod, container) (container_memory_rss{instance=~\"[[instance]].*\",namespace=~\"[[namespace]]\",container=~\"[[container]]\",container!=\"\"})",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    }
   ]
  },
  {
   "title": "[[instance]] Pod Open Sockets",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 49 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (namespace, pod, container) (container_sockets{instance=~\"[[instance]].*\",namespace=~\"[[namespace]]\",container=~\"[[container]]\",container!=\"\"})",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    }
   ]
  },
  {
   "title": "[[instance]] Pod Threads",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 53 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (namespace, pod, container) (container_threads{instance=~\"[[instance]].*\",namespace=~\"[[namespace]]\",container=~\"[[container]]\",container!=\"\"})",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    }
   ]
  },
  {
   "title": "[[instance]] Pod CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 57 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{instance=~\"[[instance]].*\",namespace=~\"[[namespace]]\",container=~\"[[container]]\",container!=\"\"}[5m])) by (namespace, pod, container) / sum(increase(container_cpu_cfs_periods_total[5m])) by (namespace, pod, container)",
     "legendFormat": "{{namespace}} / {{pod}} / {{ container }}"
    }
   ]
  },
  {
   "title": "[[instance]] Pod CPU > Requests",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 61 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (namespace, pod, container) (irate(container_cpu_usage_seconds_total{instance=~\"[[instance]].*\",namespace=~\"[[namespace]]\",container=~\"[[container]]\",container!=\"\"}[5m]) / on (namespace, pod, container) group_left max by (namespace, pod, container) (kube_pod_container_resource_requests{resource=\"cpu\"}) > 1)",
     "legendFormat": "{{namespace}} / {{pod}} / {{ container }}"
    }
   ]
  },
  {
   "title": "[[instance]] POD CPU > 85% Limits",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 65 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (namespace, pod, container) (irate(container_cpu_usage_seconds_total{instance=~\"[[instance]].*\",namespace=~\"[[namespace]]\",container=~\"[[container]]\",container!=\"\"}[5m]) / on (namespace, pod, container) group_left max by (namespace, pod, container) (kube_pod_container_resource_limits{resource=\"cpu\"}) > 0.85)",
     "legendFormat": "{{namespace}} / {{pod}} / {{ container }}"
    }
   ]
  },
  {
   "title": "[[instance]] POD Memory > Requests",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 69 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (namespace, pod, container) (container_memory_rss{instance=~\"[[instance]].*\",namespace=~\"[[namespace]]\",container=~\"[[container]]\",container!=\"\"} / on (namespace, pod, container) group_left max by (namespace, pod, container) (kube_pod_container_resource_requests{resource=\"memory\"}) > 1)",
     "legendFormat": "{{namespace}} / {{pod}} / {{ container }}"
    }
   ]
  },
  {
   "title": "[[instance]] POD Memory > 85% Limits",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 73 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (namespace, pod, container) (container_memory_rss{instance=~\"[[instance]].*\",namespace=~\"[[namespace]]\",container=~\"[[container]]\",container!=\"\"} / on (namespace, pod, container) group_left max by (namespace, pod, container) (kube_pod_container_resource_limits{resource=\"memory\"}) > 0.85)",
     "legendFormat": "{{namespace}} / {{pod}} / {{ container }}"
    }
   ]
  }
 ]
}