{
 "title": "HELM / Pods",
 "tags": [ "helm" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_last_seen{namespace=\"$namespace\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(kube_pod_start_time{namespace=~\"$namespace\", container=~\".*$container.*\"}) by (namespace, pod) * 1000"
    },
    {
     "expr": "max(kube_pod_status_phase{namespace=~\"$namespace\", container=~\".*$container.*\"}) by (namespace, pod, phase) > 0"
    },
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}[5m])) by (namespace, pod, container)"
    },
    {
     "expr": "max(container_memory_rss{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}) by (namespace, pod, container)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}[5m])) by (namespace, pod, container)"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}[5m])) by (namespace, pod, container)"
    },
    {
     "expr": "sum(irate(container_fs_reads_total{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}[5m])) by (namespace, pod, container)"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}[5m])) by (namespace, pod, container)"
    },
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}[5m])) by (namespace, pod, container)"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}[5m])) by (namespace, pod, container)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}[5m])) by (namespace, pod, container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}) by (namespace, pod, container)"
    },
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}[5m])) by (namespace, pod, container) / sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"$namespace\"}) by (namespace, pod, container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}) by (namespace, pod, container)"
    },
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}[5m])) by (namespace, pod, container) / sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"$namespace\"}) by (namespace, pod, container)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}) by (namespace, pod, container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}) by (namespace, pod, container)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}) by (namespace, pod, container) / sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}) by (namespace, pod, container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}) by (namespace, pod, container)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}) by (namespace, pod, container) / sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}) by (namespace, pod, container)"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "max(kube_pod_container_status_last_terminated_reason{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}) by (namespace, pod, container, reason) > 0"
    }
   ]
  },
  {
   "title": "CPU (cores)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}[5m])) by (namespace, pod, container)",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    }
   ]
  },
  {
   "title": "Memory (RSS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (namespace, pod, container) (container_memory_rss{inamespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"})",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    }
   ]
  },
  {
   "title": "Open Sockets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (namespace, pod, container) (container_sockets{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"})",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (namespace, pod, container) (container_threads{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"})",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (namespace, pod, container, reason) (kube_pod_container_status_last_terminated_reason{namespace=~\"$namespace\", container=~\".*$container.*\", container!=\"\"}) > 0",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}: {{ reason }}"
    }
   ]
  }
 ]
}