{
 "title": "HELM / Pods Resources",
 "tags": [ "helm" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_last_seen{namespace=\"$namespace\"}, container)"
    }
   },
   { "name": "pod" }
  ]
 },
 "panels": [
  {
   "title": "Pod CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (namespace, pod, container) (irate(container_cpu_usage_seconds_total{namespace=~\"[[namespace]]\",pod=~\".*[[pod]].*\",container=~\"[[container]]\",container!=\"\"}[5m]))",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=~\"[[namespace]]\",container=\"[[container]]\",resource=\"cpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (namespace, pod, container) (container_memory_rss{namespace=~\"[[namespace]]\",pod=~\".*[[pod]].*\",container=~\"[[container]]\",container!=\"\"})",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=~\"[[namespace]]\",container=\"[[container]]\",resource=\"memory\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Network",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"[[namespace]]\",pod=~\".*[[pod]].*\",job=\"kubelet\", metrics_path=\"/metrics/cadvisor\"}[5m])) by (namespace, pod)",
     "legendFormat": "{{ namespace }} / {{ pod }} - transmit"
    },
    {
     "expr": "sum(-irate(container_network_receive_bytes_total{namespace=~\"[[namespace]]\",pod=~\".*[[pod]].*\",job=\"kubelet\", metrics_path=\"/metrics/cadvisor\"}[5m])) by (namespace, pod)",
     "legendFormat": "{{ namespace }} / {{ pod }} - receive"
    }
   ]
  },
  {
   "title": "Pod Open Sockets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (namespace, pod, container) (container_sockets{namespace=~\"[[namespace]]\",pod=~\".*[[pod]].*\",container=~\"[[container]]\",container!=\"\"})",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    }
   ]
  },
  {
   "title": "Pod Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (namespace, pod, container) (container_threads{namespace=~\"[[namespace]]\",pod=~\".*[[pod]].*\",container=~\"[[container]]\",container!=\"\"})",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    }
   ]
  },
  {
   "title": "POD CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=~\"[[namespace]]\",pod=~\".*[[pod]].*\",container=~\"[[container]]\",container!=\"\"}[15m])) by (namespace, pod, container) / sum(increase(container_cpu_cfs_periods_total[15m])) by (namespace, pod, container)\n",
     "legendFormat": "{{ namespace }} / {{ pod }} / {{ container }}"
    }
   ]
  }
 ]
}